sudo: required
language: python

services:
  - docker

env:
  matrix:
    - DOCKER_VERSION=1.9.1-0~trusty
    - DOCKER_VERSION=1.10.1-0~trusty
    - DOCKER_VERSION=1.11.1-0~trusty

python:
  - "2.7"

before_install:  
    - ./.validateDCO
    # list docker-engine versions
    - apt-cache madison docker-engine

    # upgrade docker-engine to specific version
    - sudo apt-get -o Dpkg::Options::="--force-confnew" install -y docker-engine=${DOCKER_VERSION}
    # might as well upgrade pip to support TLS and get rid of the warnings
    - pip install --upgrade pip
    - pip install codecov pytest-cov

# command to install dependencies
# TODO: having issues with the bottle package if we don't run sudo pip install.
# It's mysterious and should be fixed eventually.
install:
  - pip install -r requirements-test.txt
  - sudo pip install -r requirements-test.txt
  
# command to run tests
script:
  - sudo python setup.py test --addopts '--cov=.'

after_success:
  - flake8 --count --exit-zero --max-complexity=10 --statistics .
  - pylint crawler
  - codecov
